### ISSUE TITLE
Cant Open Backpack

### ISSUE THREAD

**Issue by kaffeekirsche** [Mpcs/BackpacksMod#4]
Try opening Backpack give an error

> `[19:31:50] [main/FATAL]: Error executing task on Client
> io.netty.util.IllegalReferenceCountException: refCnt: 0
> 	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1417) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
> 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1403) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
> 	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:786) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
> 	at net.minecraft.class_2540.readInt(class_2540.java:1026) ~[intermediary-minecraft-1.14.2-client.jar:?]
> 	at io.github.mpcs.container.BackpackContainer.<init>(BackpackContainer.java:21) ~[Mpcs'+Backpacks+v1.1.2+-+1.14.2.jar:?]
> 	at io.github.mpcs.container.BackpackScreen.<init>(BackpackScreen.java:16) ~[Mpcs'+Backpacks+v1.1.2+-+1.14.2.jar:?]
> 	at io.github.mpcs.BackpacksModClient.lambda$onInitializeClient$1(BackpacksModClient.java:16) ~[Mpcs'+Backpacks+v1.1.2+-+1.14.2.jar:?]
> 	at net.fabricmc.fabric.impl.client.gui.ScreenProviderRegistryImpl.lambda$null$1(ScreenProviderRegistryImpl.java:75) ~[20ab54d9-5240-4765-a1ef-a1ca8a7b7046.jar:?]
> 	at net.minecraft.class_1255.method_18859(class_1255.java:159) [intermediary-minecraft-1.14.2-client.jar:?]
> 	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.14.2-client.jar:?]
> 	at net.minecraft.class_1255.method_16075(class_1255.java:130) [intermediary-minecraft-1.14.2-client.jar:?]
> 	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-minecraft-1.14.2-client.jar:?]
> 	at net.minecraft.class_310.method_1523(class_310.java:915) [intermediary-minecraft-1.14.2-client.jar:?]
> 	at net.minecraft.class_310.method_1514(class_310.java:411) [intermediary-minecraft-1.14.2-client.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:154) [intermediary-minecraft-1.14.2-client.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-loader-0.4.8+build.154.jar:?]
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) [fabric-loader-0.4.8+build.154.jar:?]
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.4.8+build.154.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

**Comment by Mpcs** [comment]
Have you changed your backpack sizes? If so, what are they? 
I have tested this version and it works fine. Have you done anything to this backpack? Like, changed name or something? Are you maybe holding something else in your other hand? I can't reproduce this bug.

**Comment by Mpcs** [comment]
Or maybe you have other mods too, list them please if you can

**Comment by kaffeekirsche** [comment]
**Mods:**
  antiqueatlas-5.0.4-fabric
  appleskin-mc1.14-fabric-1.0.6
  Autofish-0.8.4-fabric-mc1.14
  Bamboo-Mod-0.2.0
  beach-slimes-1.2.0+mc1.14.1
  blockus-1.1.11
  bouncylife-1.1.2+1.14.1
  carrots-1.4.0
  chunk-activator-1.1.1+mc1.14.2
  composable-automation-0.5.0+mc1.14.2
  cotton-0.7.0+1.14.2-SNAPSHOT
  CursedChests-2.3.18
  epicurean-gastronomy-2.2.0+1.14.1
  extra-pressure-plates-1.1.2
  fabric-api-0.3.0-pre+build.157a
  fabric-furnaces-1.1.4
  fabric-language-kotlin-1.3.31+build.4
  foamfix-0.12.1
  glassential-fabric-1.14-1.0.0
  Harvest-1.14-fabric-1.0.4
  Hwyla-fabric-1.14-1.9.16-60
  illuminations-0.1.7-1.14.1
  lead-villagers-1.1.0+mc1.14.1
  level-up-hp-4.3.0+mc1.14.2
  LightOverlay-1.2.8
  lil-tater-1.0.2
  ModMenu-1.5.4-85
  mousewheelie-1.1.14+1.14.2
  Mpcs'+Backpacks+v1.1.2+-+1.14.2
  netherthings-1.1.2
  optifabric-0.2.0
  preview_OptiFine_1.14.2_HD_U_F1_pre6
  proletarian-0.9.0+mc1.14.2
  RoughlyEnoughItems-2.9.1+build.121
  simple_pipes-0.1.5
  sodden-1.0.1.2
  stockpile-1.0.6+1.14.1
  vanilladeathchest-1.14-1.9.2.1-fabric
  vanilla-hammers-1.3.3
  vanilla-toolsets-1.1.2
  VoxelMap-1.9.4_for_1.14(.2)
  wool-1.3.6-1.14.1

**And this is my Config**

{
  "small_backpack": 9,
  "medium_backpack": 18,
  "big_backpack": 27
}

Hope it help to locate the error source

**Comment by kaffeekirsche** [comment]
I have fixed my Problem by Updating fabric-api-0.3.0 to latest version. Now all Mods with Custom Huds/Interfaces are working. 

I think i can close this issue

**Comment by Mpcs** [comment]
Oh, I see, great 👍
