### ISSUE TITLE
Crash on Launch (1.14.4)

### ISSUE THREAD

**Issue by hsrco** [Mpcs/BackpacksMod#5]
Hey folks, I'm sorry if this seems noob-ish, and sorry if I'm posting this in the wrong place, but I'm trying to install this mod onto my 1.14.4 version. Other than this mod, Fabric, and a mod called Mouse Wheely (similar to InvTweaks), my game is vanilla MC 1.14.4 and is launched and configured through MultiMC. The game fails to run, throws me back to MMC, and spits out a crash report, which I will attatch for your viewing. I was wondering if someone could tell me what is going on? Thanks in advance.
I am available to give further information about my install.

[crash-2019-10-05_20.36.31-client.txt](https://github.com/Mpcs/BackpacksMod/files/3693643/crash-2019-10-05_20.36.31-client.txt)

**Comment by hsrco** [comment]
I figured I should add, I downloaded the mod from CurseForge, and chose the most recent version which said it was for version 1.14.4.

**Comment by Mpcs** [comment]
Have you downloaded the Fabric Api (https://www.curseforge.com/minecraft/mc-mods/fabric-api) and put it in your "mods" folder? You need it to run any mod
